### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by hugofabricio** [CakeDC/i18n#28]
How do I display the default language is not the language in the url. 

example

Wishing url like this: www.domain.com 

instead of www.domain.com/eng

**Comment by hgnelson83** [comment]
I am going to reformulate the question.

This plugin works perfect. I want to add an exception of the language prefix url for the native language. So if my native language is english, I dont want to show it in the url. This is to avoid duplicate content.

**Comment by hugofabricio** [comment]
This same, hgnelson83.

**Comment by Didou518** [comment]
Has anyone found a solution yet ? I'm stuck....

**Comment by lorenzo** [comment]
did you guys define the `DEFAULT_LANGUAGE` constant?

**Comment by agarzon** [comment]
I can't understand this issue.

In my projects the URLS are like:

xxx.com/contact (English as default)
xxx.com/**fra**/contactez-nous (French)

So all the default language urls doesn't need the **$lang** in the URL (that's why is default)

The "trick" is in the way you define the routes, just like I mention in my previous response https://github.com/CakeDC/i18n/issues/28#issuecomment-62056347

**Comment by Megslalk** [comment]
Hi, seems like this has been solved. Closing this issue, please reopen if still needed.
